FROM jenkinsci/blueocean

ENV JENKINS_USER {{ jenkinsAdminUser }}
ENV JENKINS_PASS {{ jenkinsAdminPassword }}

# Skip initial setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY default-user.groovy /usr/share/jenkins/ref/init.groovy.d/

VOLUME /var/jenkins_home
