- name: update apt
  apt:
    update_cache: yes
  tags: [ansible]

- name: install pip
  apt: 
    name: python-pip
    state: present
  tags: [ansible]

- name: install pip3
  apt: 
    name: python3-pip
    state: present
  tags: [ansible]

- name: install jmespath for json_query
  pip:
    name: jmespath
    state: present
  tags: [ansible]
  