- name: install
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ dockerComposeVersion }}/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
    dest: "{{ dockerComposeInstallPath }}"
    timeout: 60
  tags: [docker-compose]

- name: set permissions
  file:
    path: "{{ dockerComposeInstallPath }}"
    mode: 0755
  tags: [docker-compose]
