- name: install container
  docker_container:
    name: portainer
    image: portainer/portainer
    detach: yes
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart_policy: always
  tags: [portainer]