- name: inspect volume
  shell: docker volume inspect {{volumeName}}
  register: result
  tags: [docker, docker-volume]

- name: "set {{volumeName}} volume fact"
  set_fact: 
    "{{volumeVar}}": "{{result.stdout | from_json | json_query('[0].Mountpoint')}}"
  tags: [docker, docker-volume]
