- hosts: k8smaster
  remote_user: "{{loggedIn_user}}"
  become: true
  tags: [k8s-master-setup]
  pre_tasks:
    - import_role:
        name: system
        tasks_from: swap
      vars:
        mode: "off"
  roles:
    - ansible
    - docker
    - nfs-client
    - k8s-master
