apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{nfsProvisionerName}} # or choose another name, must match deployment's env PROVISIONER_NAME'
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
mountOptions:
  - hard
  - bg
  - intr
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: {{nfsProvisionerName}} # or choose another name, must match deployment's env PROVISIONER_NAME'
reclaimPolicy: Retain
parameters:
  archiveOnDelete: "false"
mountOptions:
  - hard
  - bg
  - intr