- name: check kubelet status
  shell: ps -e | grep kubelet
  ignore_errors: yes
  register: kubeletIsRunning
  tags: [k8s-master]

- name: template config
  template:
    src: initConfig.yaml
    dest: "{{tmpFolder}}/"
    owner: "{{local_user}}"
    mode: 0644
  tags: [k8s-master]

- name: init kubeadm
  command: "kubeadm init --config={{tmpFolder}}/initConfig.yaml"
  register: kubeadmInitOutput
  when: kubeletIsRunning.stdout == ""
  tags: [k8s-master]

- name: init output
  debug:
    msg: "{{kubeadmInitOutput}}"
  when: kubeletIsRunning.stdout == ""
  tags: [k8s-master]
